# Site settings
author: Chris Ashman
title: Road to Software Engineering
header-img: img/home-bg.png
email: chrisashman96@gmail.com
copyright_name: Chris Ashman
description: > # this means to ignore newlines until "baseurl:"
  Technology's Open Road
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Cashman1396

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
